# Base configs
baseurl: "http://tuanchris.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-155030319-1"

# UI configs
title: "Tuan Nguyen's photography"
subtitle: "See the world through my lenses"
author: "Tuan Nguyen"
header:
 title: "Photography"
 subtitle: "by Tuan Nguyen"
footer:
 name: "Hi, my name is Tuan"
 bio: "I am a manager in Data Analytics from Vietnam. I have many hobbies and photography is one them. Have a peek at my life through my photography!" 
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/tuanchris/"
  twitter: "https://twitter.com/tuankid"
  instagram: "https://www.instagram.com/kidinlove"
  linkedin: "https://in.linkedin.com/in/tuanchris"
  github: "https://www.github.com/tuanchris"
